name: Build
on:
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@apimap"
          always-auth: true
      - run: |
          echo "@apimap:registry = https://npm.pkg.github.com/apimap" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
          echo "//npm.pkg.github.com/:always-auth=true" >> .npmrc
      - run: |
          npm install
          npm run build